version: '3.7'

services:
    postgres:
        container_name: pg_con
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_USER_VAL}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_VAL}
            - PGDATA=/data/postgres
        volumes:
            - postgres:/data/postgres
        networks:
            - paymentnetwork
        restart: unless-stopped  
    pgadmin:
        container_name: pga_con
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL_VAL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD_VAL}
        volumes:
            - pgadmin:/root/.pgadmin
        networks:
            - paymentnetwork
        restart: unless-stopped
    elasticsearch:
        container_name: es_con
        image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data
        environment:
            - xpack.monitoring.enabled=${xpack_monitoring_enabled_VAL}
            - xpack.watcher.enabled=${xpack_watcher_enabled_VAL}
            - ES_JAVA_OPTS=${ES_JAVA_OPTS_VAL}
            - discovery.type=${discovery_type_VAL}
        networks:
            - paymentnetwork      
    kibana:
        container_name: k_con
        image: docker.elastic.co/kibana/kibana:7.6.1
        ports:
            - "5601:5601"
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=${ElasticConfiguration_Uri_VAL}
        networks:
            - paymentnetwork
    logstash:
        container_name: l_con
        build:
            context: logstash/
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
        ports:
            - "8080:8080"
        environment:
            - LS_JAVA_OPTS=${LS_JAVA_OPTS_VAL}
        networks:
            - paymentnetwork
    
volumes:
    postgres:
    pgadmin:
    elasticsearch-data:
