FROM mcr.microsoft.com/dotnet/core/sdk:3.1.201-buster AS build
WORKDIR /src
COPY ["PaymentService.csproj", "PaymentService/"]
RUN dotnet restore "PaymentService/PaymentService.csproj"
COPY . ./PaymentService
WORKDIR /src/PaymentService
RUN dotnet build "PaymentService.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "PaymentService.csproj" -c Debug -o /app/publish

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-buster-slim AS final
ENV ASPNETCORE_URLS=http://*:8080
ENV ASPNETCORE_ENVIRONMENT=Development
EXPOSE 8080
# EXPOSE 443
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PaymentService.dll"]
LABEL version="1.0" maintainer="rami.vemula@thoughtworks.com"
