FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-buster-slim AS final
EXPOSE 8080
# EXPOSE 443
WORKDIR /app
COPY ./release/paymentservice.dll ./
ENTRYPOINT ["dotnet", "PaymentService.dll"]
LABEL version="1.0" maintainer="rami.vemula@thoughtworks.com"
